pre-release

diff --git a/scripts/create-release b/scripts/create-release
--- a/scripts/create-release
+++ b/scripts/create-release
@@ -2,10 +2,8 @@
 set -o errexit -o errtrace -o noclobber -o nounset -o pipefail
 IFS=$'\n\t'
 
-script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
-project_dir=$(cd $(dirname "$script_dir") && pwd)
-bold=$(tput -Txterm-256color bold)
-normal=$(tput -Txterm-256color sgr0)
+script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
+project_dir=$(cd "$(dirname "$script_dir")" && pwd)
 
 tag=${1:-}
 if [ -z "$tag" ]; then
@@ -15,25 +13,47 @@ fi
 
 cd "$project_dir"
 
-set -x
+# Configuration start
 
 module_name=dpl_pretix
-name="${module_name}-${tag}.tar.gz"
 
-function _composer() {
-  COMPOSER=composer-release.json composer "$@"
-}
+# Configuration end
 
-_composer config version "${tag}"
-_composer update
+git config --global --add safe.directory "$PWD"
+if ! git diff --exit-code composer.json; then
+  (>&2 echo; echo composer.json is changed. Aborting.)
+  exit 1
+fi
 
-rm -f "$name"
-# It seems that --files-from and --transform don't work together.
-# git ls-files | tar --create --file "$name" --exclude-from="$script_dir/build-exclude.txt" --transform "s/^\./${module_name}/" --files-from=- --show-transformed-names --verbose
-mkdir -p "$module_name"
-git ls-files | tar --create --exclude-from="$script_dir/build-exclude.txt" --files-from=- | tar --extract -C "$module_name"
-tar --create --file "$name" "$module_name"
+# Make sure that `composer.json` has the correct version.
+composer config version "${tag}"
+
+# Build release start
+
+# Build release end
+
+# Package release
+release_dir=release
+target_dir="$release_dir/$module_name"
+mkdir -p "$target_dir"
+
+rsync --verbose --archive --compress --exclude-from "$script_dir/build-exclude.txt" . "$target_dir"
+
+# Replace %%VERSION%% with actual version in build
+find $target_dir -type f -print0 | xargs -0 sed -i "s/%%VERSION%%/${tag}/g"
+
+# Strip any leading `dev-` from tag name in package name.
+name="${module_name}-${tag#dev-}.tar.gz"
+tar --create --file "$name" -C "$release_dir" $module_name
 sha256sum "$name" >| checksum.txt
-rm -fr "$module_name"
 
-git checkout composer-release.*
+# Clean up
+rm -fr $release_dir
+
+git checkout composer.json
+
+echo
+echo "Release content ($name)"
+echo
+tar tvf "$name" | grep -v '/$'
+echo
